package com.example.health.ui.assistant

import android.content.Context
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.health.R
import com.example.health.data.model.Hospital
import com.example.health.data.model.TriageResult
import com.example.health.data.remote.GeminiService
import com.example.health.data.repository.EmergencyRepository
import com.example.health.data.repository.HospitalRepository
import com.example.health.data.repository.UserPreferencesRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import javax.inject.Inject

data class AssistantMessage(
    val text: String,
    val isUser: Boolean,
    val triageResult: TriageResult? = null,
    /** True when this message was generated by Gemini AI rather than the local engine. */
    val isGeminiResponse: Boolean = false,
    /** Hospital list for rich hospital card rendering. */
    val hospitals: List<Hospital> = emptyList(),
    /** User's lat/lng at time of query, for distance calculation. */
    val userLat: Double = 0.0,
    val userLng: Double = 0.0
)

@HiltViewModel
class AssistantViewModel @Inject constructor(
    private val emergencyRepo: EmergencyRepository,
    private val hospitalRepo: HospitalRepository,
    private val userPrefsRepo: UserPreferencesRepository,
    private val geminiService: GeminiService,
    @ApplicationContext private val context: Context
) : ViewModel() {

    // Welcome message uses the Application context so it picks up the locale
    // that was applied via LocaleHelper.wrap() in attachBaseContext.
    // Result: the message is always in the currently-selected language.
    private val _messages = MutableStateFlow<List<AssistantMessage>>(
        listOf(
            AssistantMessage(
                text = context.getString(R.string.assistant_welcome),
                isUser = false
            )
        )
    )
    val messages: StateFlow<List<AssistantMessage>> = _messages.asStateFlow()

    private val _inputText = MutableStateFlow("")
    val inputText: StateFlow<String> = _inputText.asStateFlow()

    /** True while the assistant is waiting for a response (local or Gemini). */
    private val _isTyping = MutableStateFlow(false)
    val isTyping: StateFlow<Boolean> = _isTyping.asStateFlow()

    fun updateInput(text: String) {
        _inputText.value = text
    }

    fun sendMessage() {
        val text = _inputText.value.trim()
        if (text.isBlank()) return

        val userMsg = AssistantMessage(text = text, isUser = true)
        _messages.value = _messages.value + userMsg
        _inputText.value = ""
        _isTyping.value = true

        viewModelScope.launch {
            try {
                val lowerText = text.lowercase()

                // ── 1. Detect hospital queries in all supported languages ──
                val isHospitalQuery = lowerText.containsAny(
                    "hospital", "clinic", "doctor",
                    // Kannada
                    "ಆಸ್ಪತ್ರೆ", "ವೈದ್ಯ",
                    // Hindi
                    "अस्पताल", "क्लिनिक", "डॉक्टर",
                    // Gujarati
                    "હૉસ્પિટલ", "ક્લિનિક",
                    // Marathi
                    "रुग्णालय", "दवाखाना",
                    // Tamil
                    "மருத்துவமனை", "மருத்துவர்"
                )

                if (isHospitalQuery) {
                    val lat = userPrefsRepo.lastLat.first().toDouble()
                    val lng = userPrefsRepo.lastLng.first().toDouble()

                    val useLat = if (lat != 0.0) lat else 12.9716
                    val useLng = if (lng != 0.0) lng else 77.5946

                    val hospitals = hospitalRepo.getHospitalsForLocation(useLat, useLng).take(3)
                    val headerText = if (lat != 0.0 && lng != 0.0) {
                        context.getString(R.string.hospitals_near_you)
                    } else {
                        context.getString(R.string.hospitals_no_location)
                    }

                    _messages.value = _messages.value + AssistantMessage(
                        text = headerText,
                        isUser = false,
                        hospitals = hospitals,
                        userLat = useLat,
                        userLng = useLng
                    )
                    return@launch
                }

                // ── 2. Try the local keyword triage engine ──
                val result = emergencyRepo.triageQuery(text)

                if (result.matchedCategory != null) {
                    // Local engine found a match — use it directly
                    _messages.value = _messages.value + AssistantMessage(
                        text = result.message,
                        isUser = false,
                        triageResult = result
                    )
                } else {
                    // ── 3. No local match → fallback to Gemini AI ──
                    val geminiResponse = geminiService.ask(text)

                    if (geminiResponse != null) {
                        _messages.value = _messages.value + AssistantMessage(
                            text = geminiResponse,
                            isUser = false,
                            isGeminiResponse = true
                        )
                    } else {
                        // Gemini unavailable or errored — show the local fallback
                        _messages.value = _messages.value + AssistantMessage(
                            text = result.message,
                            isUser = false,
                            triageResult = result
                        )
                    }
                }
            } finally {
                _isTyping.value = false
            }
        }
    }

    private fun addBotMessage(text: String) {
        _messages.value = _messages.value + AssistantMessage(text = text, isUser = false)
    }

    private fun String.containsAny(vararg keywords: String): Boolean =
        keywords.any { this.contains(it) }
}
